title: Avaliações Ciência da Computação - UVV
description: Compilado de avaliações
theme: just-the-docs

color_scheme: dark

url: https://luwucaz.github.io/avaliacoes-uvv-cc

aux_links:
  Template Repository: https://github.com/luwucaz/avaliacoes-uvv-cc
